---
apiVersion: v1
kind: Service
metadata:
  name: log-statistics
  namespace: jujube
  labels:
    app: log-statistics
spec:
  type: ClusterIP
  selector:
    app: log-statistics
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
