---
apiVersion: v1
kind: Service
metadata:
  name: model-management
  namespace: jujube
  labels:
    app: model-management
spec:
  type: ClusterIP
  selector:
    app: model-management
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
