---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: jujube
  labels:
    app: neo4j
    app.kubernetes.io/name: jujube-platform
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5-enterprise
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "$(NEO4J_USER)/$(NEO4J_PASSWORD)"
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_server_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_server_memory_heap_max__size
              value: "1g"
            - name: NEO4J_server_memory_pagecache_size
              value: "512m"
          envFrom:
            - secretRef:
                name: jujube-secrets
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
