---
apiVersion: v1
kind: Service
metadata:
  name: reasoning-engine
  namespace: jujube
  labels:
    app: reasoning-engine
spec:
  type: ClusterIP
  selector:
    app: reasoning-engine
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
