---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-registry-pvc
  namespace: jujube
  labels:
    app.kubernetes.io/name: jujube-platform
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""  # use default StorageClass

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-pvc
  namespace: jujube
  labels:
    app.kubernetes.io/name: jujube-platform
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
